### ISSUE TITLE
Create A Simple Resume Website For Me

### ISSUE THREAD

**Issue by gurjarmanoj** [gurjarmanoj/gurjarmanoj.github.io#1]
Name: Manoj Kumar Gurjar
Skills: Java, C++, JavaScript, PostgreSQL, Python, Flask, Angular Js
College: Government Engineering College, Ajmer 
Branch and YOP: (Mechanical Engineering) (2016-20)

**Comment by NoelBank** [comment]
wait what? this ins't a real Issue?

**Comment by jabo-bernardo** [comment]
What do you mean?

**Comment by NoelBank** [comment]
To create a issue for a Open Source Project you should have started with something, you can't not doing the work entirely by someone else
